# Codevoorbeelden

De bedoeling van deze directory is om hier codevoorbeelden in R te verzamelen van alle concepten die in de cursus aan bod komen. De voorbeelden zijn opgesplitst per cursushoofdstuk.

Als je een verzoek hebt voor een toevoeging, of een aanpassing/verbetering, aarzel niet om een Issue aan te maken!

De documenten zijn opgemaakt in R Markdown (.Rmd) die toelaat om een opgemaakt HTML, PDF of Word-document te genereren met een combinatie van tekst, R broncode en zelfs formules in LaTeX-notatie. Als je het .Rmd-document in RStudio opent, kan je op de knop "Knit" klikken om te converteren in één van de drie ondersteunde formaten. De HTML-versie is al in de repository opgenomen.

## Knit package instaleren in R-Studio

"Knit" is waarschijnlijk nog niet geïnstalleerd in R-studio.
Ga naar "Tools" -> "Install Packages" en tik "knitr".
Zorg ervoor dat "Install dependencies" aangevinkt is.

## Overzicht

- [Hoofdstuk 1: Aan de slag](1-aan-de-slag.html)
- [Hoofdstuk 2: Het onderzoeksproces](2-onderzoeksproces.html)
  - Steekproef, importeren datasets, werken met data table/tibble.
- Hoofdstuk 3: Analyse van 1 variabele
  - [Centrum- en spreidingsmaten](3-analyse-1-variabele.html)
  - [Visualisatietechnieken](3-visualisatie-1-variabele.html)
- [Hoofdstuk 4: De centrale limietstelling](4-centrale-limietsetlling.html)
- [Hoofdstuk 5: Toetsingsprocedures](5-toetsingsprocedures.html)
- Hoofdstuk 6: Analyse van 2 variabelen
  - Verband tussen 2 kwalitatieve variabelen: Chi-kwadraat; Cramér's V
  - Verband tussen kwalitatieve en kwantitatieve variabele: t-toets voor 2 steekproeven en Cohen's d
  - Verband tussen 2 kwantitatieve variabelen: regressie-analyse
- Hoofdstuk 7: Tijdreeksen
